apiVersion: apps/v1
kind: Deployment
metadata:
  name: tape-manager
  namespace: tape-manager
  labels:
    app: tape-manager
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 0
  selector:
    matchLabels:
      app: tape-manager
  template:
    metadata:
      labels:
        app: tape-manager
    spec:
      containers:
      - name: tape-manager
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      dnsPolicy: ClusterFirst
      restartPolicy: Always

