apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tape-manager
  namespace: tape-manager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tape-manager
    namespace: tape-manager
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 10
