apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: tape-manager
  namespace: tape-manager
spec:
  minReplicas: 1
  maxReplicas: 20 
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: tape-manager
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
