apiVersion: v1
kind: Service
metadata:
  name: tape-manager
  namespace: tape-manager
spec:
  selector:
    app: tape-manager
  ports:
    - name: http
      protocol: TCP
      port: 80
  type: NodePort
